apiVersion: batch/v1
kind: Job
metadata:
  name: helloworld
spec:
  completions: 4
  parallelism: 2
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["echo", "Helloo Kube!!!"]
      restartPolicy: Never
