apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset
  labels:
    k8s-app: logging
spec:
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: varlog
          mountPath: /mnt
      volumes:
      - name: varlog
        hostPath:
          path: /nfs/client
