apiVersion: apps/v1
kind: Deployment
metadata:
  name: with-pod-affinity
  labels:
    run: tier
spec:
  replicas: 4
  selector:
   matchLabels:
     run: tier
  template:
    metadata:
      labels:
        run: tier
    spec:
     containers:
      - name: with-pod-affinity
        image: nginx
     affinity:
      nodeAffinity:
       requiredDuringSchedulingIgnoredDuringExecution:
         nodeSelectorTerms:
         - matchExpressions:
           - key: app
             operator: In
             values:
             - tier
