apiVersion: apps/v1
kind: Deployment
metadata:
  name: with-pod-affinity
  labels:
    run: tier
spec:
  replicas: 3
  selector:
   matchLabels:
     run: tier
  template:
    metadata:
      labels:
        run: tier
    spec:
     containers:
      - name: with-pod-affinity
        image: nginx
     affinity:
       podAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: color
                operator: In
                values:
                 - red
            topologyKey: topology.kubernetes.io/zone
