apiVersion: apps/v1
kind: Deployment
metadata:
  name: with-node-affinity
  labels:
    run: tier
spec:
  replicas: 3
  selector:
   matchLabels:
     run: tier
  template:
    metadata:
      labels:
        run: tier
    spec:
     containers:
      - name: with-node-affinity
        image: nginx
     tolerations:
      - key: "type"
        operator: "Equal"
        value: "prod"
        effect: "NoSchedule"
     affinity:
      nodeAffinity:
       requiredDuringSchedulingIgnoredDuringExecution:
         nodeSelectorTerms:
         - matchExpressions:
           - key: app
             operator: In
             values:
             - tier
