apiVersion: v1
kind: Pod
metadata:
  name: with-pod-affinity
spec:
  affinity:
    podAffinity: 
      preferredDuringSchedulingIgnoredDuringExecution: 
         - labelSelector:
            matchExpressions:
            - key: color 
              operator: In 
              values:
              - green
          topologyKey: kubernetes.io/hostname
  containers:
  - name: with-pod-affinity
    image: nginx
