apiVersion: v1
kind: Pod
metadata:
  name: sec-capability
  namespace: default
spec:
  securityContext:
    runAsUser: 3000
  containers:
  - image: gcr.io/google-samples/node-hello:1.0
    name: alpine
    securityContext:
      capabilities:
        drop: ["NET_RAW"]
