apiVersion: v1
kind: Pod
metadata:
  name: sec-capability
  namespace: default
spec:
  containers:
  - image: alpine
    name: alpine
    securityContext:
      capabilities:
        drop: ["all"]
        add: ["NET_BIND"]
